const SAMPLE_TASKS_DATA = [
  {
    id: '',
    title: 'Templates and Design',
    description: 'Create and design the main templates.',
    assignedTo: [],
    dueDate: '',
    prio: 'medium',
    category: '',
    subtasks: [
      {
        index: '',
        text: 'Create the summary template',
        done: true,
        focussed: false,
      },
      {
        index: '',
        text: 'Create the add-task template',
        done: true,
        focussed: false,
      },
      {
        index: '',
        text: 'Create the board template',
        done: true,
        focussed: false,
      },
      {
        index: '',
        text: 'Create the contacts template',
        done: true,
        focussed: false,
      },
    ],
    column: '',
  },
  {
    id: '',
    title: 'Logic',
    description: '',
    assignedTo: [],
    dueDate: '',
    prio: 'medium',
    category: '',
    subtasks: [],
    column: '',
  },
  {
    id: '',
    title: 'Privacy Policy and Legal Notice',
    description: '',
    assignedTo: [],
    dueDate: '',
    prio: 'low',
    category: '',
    subtasks: [],
    column: '',
  },
  {
    id: '',
    title: 'Clean Coding und JSDoc',
    description: '',
    assignedTo: [],
    dueDate: '',
    prio: 'medium',
    category: '',
    subtasks: [],
    column: '',
  },
  {
    id: '',
    title: 'Feedback and Submission',
    description: '',
    assignedTo: [],
    dueDate: '',
    prio: 'urgent',
    category: '',
    subtasks: [],
    column: '',
  },
];
